name: AI News Tweeter

on:
  schedule:
    # Run at 6:00 AM JST (21:00 UTC previous day)
    - cron: '0 21 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  tweet-ai-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run AI News Tweeter
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        TINYURL_API_KEY: ${{ secrets.TINYURL_API_KEY }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      run: |
        python main.py
    
    - name: Upload logs as artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tweet-logs-${{ github.run_number }}
        path: |
          tweet_log.txt
        retention-days: 30
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "AI News Tweeter workflow failed. Check the logs for details."
        # You can add notification logic here (e.g., send email, Slack message)