name: Viral AI Tweet Generator

on:
  schedule:
    # Run at 9:00 AM JST (0:00 UTC)
    - cron: '0 0 * * *'
    # Run at 5:00 PM JST (8:00 UTC)
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-viral-tweet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate and Post Viral Tweet
      env:
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        TINYURL_API_KEY: ${{ secrets.TINYURL_API_KEY }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      run: python viral_tweet_generator.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: viral-tweet-logs-${{ github.run_number }}
        path: |
          *.log
        retention-days: 7
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "Viral tweet generation failed. Check the logs for details."
        exit 1